[DecoText]
Default=Brak danych.

AlienFemaleAA=Imię:  Mokara|Wiek:   20|Rasa:  Gen Mo'Kai||Dane:|Siostra Damarusa, druga w kolejce dziedziczka berła Mobetha. Mokara uważa, że jej brat nie jest wart tytułu i chce go przejąć, dowodząc swojej wartości w walce. Cicha i zimna cały czas obserwuje przeciwników, by znaleźć ich słabości.||
AlienFemaleAB=Imię:  Makreth|Wiek:   24|Rasa:  Gen Mo'Kai||Dane:|Wojowniczka z klanu Żółtej Kości. Makreth z dumą nosi maskę śmierci przekazywaną w jej rodzinie z pokolenia na pokolenie. Jej obnażone szpony i zaciśnięte oczy spowodowały, że niejeden przeciwnik zamarł z przerażenia.||
AlienFemaleBA=Imię:  Faraleth|Wiek:   28|Rasa:  Gen Mo'Kai||Dane:|Kiedy ludzka zaraza, zwana Szkarłatną Śmiercią, niemal całkowicie zniszczyła jej plemię, zielarka Faraleth oszalała z rozpaczy i bezsilności wobec choroby. Teraz każda śmierć, którą zadaje w trakcie turnieju, jest małym krokiem ku odkupieniu.||
AlienFemaleBB=Imię:  Nebri|Wiek:   26|Rasa:  Gen Mo'Kai||Dane:|Po tym, jak trucizna armoreańskiego drapieżnika na stałe oszpeciła jej twarz, Nebri postanowiła wziąć udział w turnieju. Nie chciała się narażać na odrzucenie ze strony własnych przyjaciół. Jej rodak Damarus nie ma pojęcia, że jej uczucia wobec niego nie są wcale takie wrogie.||
AlienMaleAA=Imię:  Damarus|Wiek:   23|Rasa:  Gen Mo'Kai||Dane:|Damarus jest synem wodza plemienia Mobeth - Gik My. Jego imię jest znane wśród bywalców aren. Jako ochotnik, korzysta z wielu fizycznych przyjemności, ale ci, którzy myślą, że jego hedonistyczne nastawienie do życia go zmiękczyło - nie widzieli go jeszcze w akcji z karabinem biologicznym.||
AlienMaleAB=Imię:  Komek|Wiek:   27|Rasa:  Gen Mo'Kai||Dane:|Podobnie jak Makreth Komek w trakcie walki używa rodzinnej maski śmierci. Tym samym zyskał pogardę Motiga, który uważa, że strach u wrogów należy wywoływać swoimi umiejętnościami, a nie groźnymi maskami.||
AlienMaleBA=Imię:  Motig|Wiek:   19|Rasa:  Gen Mo'Kai||Dane:|Najmłodszy z zawodników Gen Mo'Kai. Motig jest bardzo przychylny i otwarty wobec rekrutów. Uwielbia zapał widowni i finezyjnie miażdży wrogów ku uciesze publiki. Przecenienie jego umiejętności może być ostatnią pomyłką, jaka zdarzy ci się w życiu.||
AlienMaleBB=Imię:  Selig|Wiek:   25|Rasa:  Gen Mo'Kai||Dane:|W odróżnieniu od swojego pysznego przyjaciela Motiga Selig jest zamknięty w sobie. Pomiędzy turniejami podróżuje po światach i opisuje interesujące odkrycia. Zdarza mu się też grać w zabójczą grę w kotka i myszkę ze stworzeniami, które spotka na swej drodze.||

BotAA=Imię:  Thorax|Wiek:   N/A|Rasa:  Sztuczna forma życia||Dane:|Bezwzględny w zawodach, posiada cyfrową nieśmiertelność, której stworzenia organiczne nie rozumieją. Thorax ma tylko jeden cel: zwycięstwo.||
BotAB=Imię:  Mandible|Wiek:   N/A|Rasa:  Sztuczna forma życia||Dane:|Programista, który stworzył Mandibla, uznał, że interesującym eksperymentem byłoby kazać mu się zastanowić nad własnym istnieniem. Trzy dni później, po zabiciu 76 ludzi, automat wciąż nie znalazł odpowiedzi, ale za to dogłębnie poznał ludzką anatomię.||
BotBA=Imię:  Widowmaker|Wiek:   N/A|Rasa:  Sztuczna forma życia||Dane:|Widowmaker to jeden z nielicznych robotów bojowych, nie mający żadnych elementów organicznych. Zaawansowane procedury wykrywania zagrożenia i system uników oznaczają, że należy się z nim liczyć.||
BotBB=Imię:  Syzygy|Wiek:   N/A|Rasa:  Sztuczna forma życia||Dane:|Syzygy nadaje terminowi 'ostry jak brzytwa' zupełnie nowe znaczenie.||
BotCA=Imię:  Cobalt|Wiek:   N/A|Rasa:  Sztuczna forma życia||Dane:|Każdy żołnierz szkoli się w walce z robotami, by doprowadzić umiejętność celowania do perfekcji. A co by się stało, gdyby robot był mądrzejszy, silniejszy i wziął na celownik właśnie ciebie?||
BotCB=Imię:  Rapier|Wiek:   N/A|Rasa:  Sztuczna forma życia||Dane:|Szatkuje, kroi w plastry, wypruwa wnętrzności, dekapituje, widzi w ciemnościach i może cię namierzyć po DNA. Coś jak dziewczyna, z którą nie chciałeś iść na studniówkę.||
BotDA=Imię:  Corrosion|Wiek:   N/A|Rasa:  Sztuczna forma życia||Dane:|Pod pancerzem zimnego metalu płonie dusza tak jasna, jak blask ginącej gwiazdy. To dusza istoty, która chciała niegdyś podbić galaktykę dla Imperatora. Marzenia Corrosiona przeminęły tak, jak jego ginące ciało. Teraz szuka tylko zemsty.||
BotDB=Imię:  Renegade|Wiek:   N/A|Rasa:  Sztuczna forma życia||Dane:|Opcja miłosierdzia została usunięta z systemu operacyjnego tego robota przy okazji niedawnej aktualizacji.||

EgyptFemaleAA=Imię:  Diva|Wiek:   18|Rasa:  Człowiek||Dane:|Znana ze swego uroku i charyzmy zarówno na arenie, jak i poza nią, Diva ma reputację osoby niezwykle zdeterminowanej w pościgu za zwycięstwem. Bardzo bawią ją karteczki z wyrazami współczucia, które osobiście dostarcza przeciwnikom przed meczem.||
EgyptFemaleAB=Imię:  Memphis|Wiek:   21|Rasa:  Człowiek||Dane:|Niegdyś przepiękna dziedziczka arystokratycznego rodu. Memphis znudziła się pustym istnieniem i przeniosła na arenę, gdzie została zaprawionym w bojach wojownikiem uzależnionym od adrenaliny i walki o przetrwanie.
EgyptFemaleBA=Imię:  Asp|Wiek:   25|Rasa:  Człowiek||Dane:|Piękna i zabójcza. Asp jest szybka jak żmija. Możesz być pewny, że po jej ugryzieniu ofiara nie przeżyje.||
EgyptFemaleBB=Imię:  Cleopatra|Wiek:   25|Rasa:  Człowiek||Dane:|Jeśli uważasz, że Cleopatra i Asp mają coś wspólnego, możesz mieć rację. Ale z tym czymś lepiej nie zaczynać, jeśli nie trzymasz w rękach giwery.||
EgyptMaleAA=Imię:  Scarab|Wiek:   24|Rasa:  Człowiek||Dane:|Porucznik Pustynnego Legionu i weteran trzech wojen plemiennych. Scarab to zimny i kalkulujący taktyk, który lubi wywabiać przeciwników na otwarte pole, gdzie może ich zabić dla własnej przyjemności.||
EgyptMaleAB=Imię:  Horus|Wiek:   28|Rasa:  Człowiek||Dane:|Ród Horusa walczy na arenie od trzech pokoleń, co zapewniło mu popularność wśród publiczności i respekt u przeciwników. Zaprasza chętne panie na prywatne sesje podpisywania autografów po dzisiejszym meczu.||
EgyptMaleBA=Imię:  Roc|Wiek:   27|Rasa:  Człowiek||Dane:|Były oficer Strażników Świątynnych. Roc uznał, że to stanowisko nie odpowiada jego ambicjom - bardzo niska przestępczość w mieście oznaczała długie i nudne godziny służby. Oficer werbunkowy Imperium zachęcił go do opuszczenia rodzinnej planety i rozpoczęcia kariery w galaktyce.||
EgyptMaleBB=Imię:  Hyena|Wiek:   27|Rasa:  Człowiek||Dane:|Dla wojowników północnych pustkowi wyrażanie emocji to oznaka słabości. Hyena nigdy w życiu nie uronił łzy - tam skąd pochodzi kropla wody jest cenniejsza, niż kropla krwi. Urodzony, by walczyć na piaskach pustyni, teraz walczy, by móc wrócić w rodzinne strony.||

JuggFemaleAA=Imię:  Rylisa|Wiek:   32|Rasa:  Homo Sapiens|       (po terapii genowej)||Dane:|Była przywódczyni Związku Zawodowego Górników Rudy #732RG. Rylisa doszła do wniosku, że łapówki oferowane jej przez przedstawicieli Imperium są zniewagą. Odcięła więc obie dłonie jednemu z wysłanników i skorzystała z jego podskórnego chipu identyfikacyjnego, by zyskać dostęp do jego konta. Dzięki tak zdobytej fortunie skończyła z życiem w zmrożonych lodem kopalniach.||
JuggFemaleAB=Imię:  Reinha|Wiek:   29|Rasa:  Homo Sapiens|       (po terapii genowej)||Dane:|Po śmierci męża w wypadku górniczym Reinha straciła sens życia. Przyjęła więc imię, które ukochany nadał jej w swym ojczystym języku, portugalskim, i wyruszyła na poszukiwania sensu śmierci.||
JuggFemaleBA=Imię:  Ambrosia|Wiek:   26|Rasa:  Homo Sapiens|       (po terapii genowej)||Dane:|Mistrzyni w podnoszeniu ciężarów, która w napadzie szału po terapii genowej udusiła sędziego. Postanowiła więc wycofać się z tej dyscypliny i spróbować swych sił w Turnieju.||
JuggFemaleBB=Imię:  Siren|Wiek:   27|Rasa:  Homo Sapiens|       (po terapii genowej)||Dane:|Los nie tylko poskąpił jej urody (i to w ekstremalnym znaczeniu), ale także wprowadził do jej genów DNA drzewa. Siren chętnie usłyszy, że nie ma w niej nic pięknego. Będzie bowiem mogła z czystym sumieniem skopać ci tyłek.||
JuggMaleAA=Imię:  Gorge|Wiek:   34|Rasa:  Homo Sapiens|       (po terapii genowej)||Dane:|Tylko prawdziwi twardziele są w stanie przeżyć w ciężkich warunkach Kolonii Karnej Allerian.||Są jednak tacy, którzy takie warunki lubią.||Gorge ma niesamowity instynkt przetrwania i uwielbia zadawać ból. Niegdyś osadzony w więzieniu szybko skorzystał z okazji, by wziąć udział w Turnieju. Swoje umiejętności bojowe szlifował zarówno na arenie, jak i poza nią. Brak ciężkiej broni w kopalniach więziennych bynajmniej nie wpłynął na jego wyszkolenie.||Po co komu giwera, kiedy ma ręce i zęby?||
JuggMaleAB=Imię:  Frostbite|Wiek:   37|Rasa:  Homo Sapiens|       (po terapii genowej)||Dane:|Jego mroźne spojrzenie poczujesz z daleka, niczym gangrenę w swoim ciele. To spojrzenie cię ogarnie, zechce zmienić twoją krew w lód, a twoje serce w kamień. Wyobraź więc sobie, co zrobi sam Frostbite, kiedy dorwie cię w swoje ręce.||
JuggMaleBA=Imię:  Cannonball|Wiek:   28|Rasa:  Homo Sapiens|       (po terapii genowej)||Dane:|Gdyby zgniatarka do śmieci i czołg mogli mieć dziecko, to tym dzieckiem byłby Cannonball. Wielki, brzydki, z charakterkiem chorego na wściekliznę grizzly. Tylko samobójca zgłosiłby się na ochotnika do przebywania w jednej celi z tym zatwardziałym kryminalistą.||
JuggMaleBB=Imię:  Arclite|Wiek:   24|Rasa:  Homo Sapiens|       (po terapii genowej)||Dane:|W odróżnieniu od swych towarzyszy Arclite nie jest ani kryminalistą ani żądnym krwi mordercą. Jego występy w Turnieju są efektem ubocznym jego genetycznego makijażu. Uważaj jednak i nie wchodź mu w drogę - Arclite naprawdę nie lubi tych występów.||

MercFemaleAA=Imię:  Prism|Wiek:   26|Rasa:  Człowiek||Dane:|Prism wychowana na uszkodzonym statku flagowym 7 floty najemniczej pracuje jako inżynier i cyngiel do wynajęcia. Sama opracowała cybernetyczną przepaskę na oko, której początkowo używała do badania mikropęknięć w kontenerach transportowych.||
MercFemaleAB=Imię:  BlackJack|Wiek:   26|Rasa:  Człowiek||Dane:|Nie zapatrz się w te piękne oczy. Jest twarda jak stal i daje sobie radę na arenie lepiej, niż niejeden mężczyzna. Była zwiadowcą oddziałów najemniczych i tam - już jako dziecko - zdobyła reputację. Jest ceniona za solidność i odwagę.||
MercFemaleBA=Imię:  Sapphire|Wiek:   27|Rasa:  Człowiek||Dane:|Inteligentna, atrakcyjna, elokwentna, a jednocześnie brutalna na arenie. Sapphire wywołuje szybsze bicie serca u wielu wojowników i z różnych powodów.||
MercFemaleBB=Imię:  Satin|Wiek:   24|Rasa:  Człowiek||Dane:|Zaledwie dwa lata temu statek Imperialny zaatakował jednostkę jej klanu i wysłał wszystkich ludzi na pokładzie do doków niewolniczych na Briggan IV. Dyrektor doku uznał, że jest słodka i zatrzymał ją dla siebie, ale chwila nieuwagi przyniosła mu tylko zmiażdżoną krtań i szybkie podążanie w kierunku światła na końcu tunelu. Dziewczyna od razu spodobała się nadzorcy Driakowi, który od zawsze nienawidził dyrektora doku. Nadzorca wyszkolił Satin do walki w Turniejach, które od tej pory stały się jej sposobem na życie.||
MercFemaleCA=Imię:  Lauren|Wiek:   34|Rasa:  Człowiek||Dane:|Zadziorna, lojalna i zwinna. Lauren może jest szczupła, ale za to ma niesamowity refleks. Wychowana w biednej rodzinie górniczej zyskała sławę, gdy po cichu wykończyła konkurentów swoich rodziców. Następnie została wojownikiem turniejowym na cały etat. Jej słaby punkt? Ponoć zrobi wszystko, by obronić swojego ukochanego ze szkoły średniej, Brocka.||

MercMaleAA=Imię:  Wraith|Wiek:   27|Rasa:  Człowiek ||Dane:|Wraith brał udział w turniejach od czasu, gdy skończył 19 lat. Widział najbardziej zacięte pojedynki w historii.|Biorąc pod uwagę jego doświadczenie w walce i liczbę kontuzji, które odnieśli przeciwnicy, nasuwa się pytanie, co jest bardziej naznaczone bliznami - jego ciało czy umysł?||
MercMaleAB=Imię:  Torch|Wiek:   28|Rasa:  Człowiek||Dane:|Torch jest małomówny, ale jeśli chcesz mu wydać rozkaz, lepiej nie krzycz. Jeśli Torch się z kimś nie zgadza, spór rozwiązuje za pomocą giwery.||
MercMaleBA=Imię:  Romulus|Wiek:   26|Rasa:  Człowiek||Dane:|Wspierany przez brata-bliźniaka Romulus nieraz udowodnił, że z odpowiednią drużyną dobry dowódca może zajść wysoko. I co z tego, że brat czasem jest zazdrosny i zaczyna do niego strzelać? Zbiornik klonujący wynaleziono nie bez powodu, prawda?||
MercMaleBB=Imię:  Remus|Wiek:   26|Rasa:  Człowiek||Dane:|Bycie jednym z pary bliźniaków nie jest takie złe pod warunkiem, że stoją oni po jednej stronie barykady. Jeśli uważasz, że walka na arenie z własnym bratem jest trudna, spróbuj zadrzeć z jego bratem. Na szczęście Remus jest prawdziwym frajerem, więc łatwiej z nim wygrać, niż z Romulusem.||
MercMaleCA=Imię:  Brock|Wiek:   45|Rasa:  Człowiek||Dane:|Wychowany w bogatej, marsjańskiej rodzinie Brock ukończył akademię międzygwiezdną. Plotka głosi, że zabił w trakcie szkolenia swojego mentora, ale łapówka wręczona przez ojca uspokoiła władze. Czasem nie panuje nad sobą, ale zwykle postępuje zgodnie z regulaminem.||
MercMaleDA=Imię:  Malcolm|Wiek:   42|Rasa:  Człowiek||Dane:|Malcolma nie trzeba przedstawiać - to największy weteran Turniejów rozpoznawany na każdej planecie. Dumny ze swego ziemskiego pochodzenia, lojalny, urodzony przywódca ze zmysłem przetrwania.||

NightFemaleAA=Imię:  Domina|Wiek:   54|Rasa:  Homo Sapiens|       Meduza||Dane:|Domina jest chodzącą pułapką, która żeruje na współczuciu swoich ofiar. Zakrada się w najczarniejsze zakątki tysiąca światów i poluje na wrogów Imperium.|Podobnie jak wszyscy członkowie Sił Czujności Domina posiada unikatową zdolność do wyczuwania zdrady tam, gdzie nikt jej nie planuje.|Niektórzy twierdzą, że słyszy własne mroczne myśli, inni, że ma łańcuchy zdrady wplecione w jej własne DNA.|Niezależnie od powodu, jeśli pewnego dnia usłyszysz głos dziecka, dobiegający z mrocznego zakątka, uciekaj i nie zatrzymuj się, póki nie stracisz oddechu.||
NightFemaleAB=Imię:  Subversa|Wiek:   38|Rasa:  Homo Sapiens|       Meduza||Dane:|Jej oczy są pozbawione życia - to puste okręgi, które badają świat tępym wzrokiem. Cienka nitka śliny bezwolnie spływa z jej ciasno zakneblowanych ust, a jednak Subversa nigdy jej nie ociera. Tę torturowaną duszę rozświetlić na moment może tylko jedna rzecz - cierpienie innych.||
NightFemaleBA=Imię:  Lilith|Wiek:   19|Rasa:  Cyberczłowiek||Dane:|W trakcie ataku na medyczny transport imperialny Lilith straciła obie nogi. Została złapana i skazana na usunięcie osobowości w ośrodku karnym Czyściec. Jej ciało i umysł zostały stworzone od początku - teraz Lilith pracuje jako łowca nagród dla Imperium.||
NightFemaleBB=Imię:  Fate|Wiek:   Nieznany|Rasa:  Cyberczłowiek||Dane:|Będąc małą dziewczynką, Fate śniła o obrzydliwych potworach i cierpieniach, jakie mogą odczuwać ludzie. Dziesiątki lat później koszmary pozostały, ale dziecięca niewinność uleciała w niepamięć.||
NightMaleAA=Imię:  Brutalis|Wiek:   24|Rasa:  Homo Sapien Taratis||Dane:|Jego siła ustępuje chyba tylko jego brzydocie. Brutalis był wynikiem eksperymentu, mającego na celu skrzyżowanie ludzi z więźniami z planety Tarat. Celem eksperymentu było stworzenie niezwykle inteligentnej maszyny do zabijania, a jego sukces przerósł wszelkie oczekiwania. Naukowcy tak się przestraszyli własnego tworu, że zarzucili projekt.||
NightMaleAB=Imię:  Ravage|Wiek:   Nieznany|Rasa:  Homo Sapien Taratis||Dane:|Gdyby przepisy Turnieju zezwalały na walkę bez użycia broni, mecze z udziałem Ravage'a byłyby krótkie i bardzo, bardzo krwawe.||
NightMaleBA=Imię:  Mr. Crow|Wiek:   około 36|Rasa:  Homo Sapiens|       Meduza||Dane:|Mr Crow chce wprowadzić styl i kulturę do najbardziej brutalnego i dekadenckiego sportu w historii. W oczach publiczności dodaje mu uroku fakt, że jest wściekłym szaleńcem ze skłonnością do dziwnych zboczeń.
NightMaleBB=Imię:  Harlequin|Wiek:   34|Rasa:  Homo Sapiens|       Meduza||Dane:|Zastanawialiście się kiedyś, dlaczego dzieci boją się klaunów? Teraz już wiecie.||

Arborea=ID planety:   JX-4230, Arborea|Typ planety: tropikalna|Śr. temp.:  27 C|Populacja:  12 milionów|Gł. pr. eksportowy: Jadalne algi|Gł. pr. importowy: Ogniwa dyfuzyjne||Planeta macierzysta rasy Gen Mo'Kai, Arborea jest rajem pełnym ogromnych dżungli i lasów. Inteligentni Gen Mo'Kai polegają przede wszystkim na technologii organicznej, ale antropologowie zauważyli wśród populacji zwiększone zainteresowanie innymi technologiami.||
Anubis=ID planety:   ME-334, Anubis|Typ planety: Pustynny księżyc|Śr. temp.:  42 C|Populacja:  43 miliony|Gł. pr. eksportowy: Krzem|Gł. pr. importowy: Woda||Niemal 3000 lat temu, kolonia ludzi z pustyni egipskiej przybyła na ten odległy księżyc w ramach eksperymentu obcych. Podczas gdy egipskie imperium na Ziemi ostatecznie się rozpadło i przeszło do historii, koloniści z Anubisa wciąż się rozwijali i stworzyli cywilizację łączącą wyjątkową architekturę przodków z nowoczesną technologią.||
Alleria=ID planety:   JX-237, Alleria|Typ planety: Świat lodu|Śr. temp.:  -20 C|Populacja:  34 716|Gł. pr. eksportowy: Iryd|Gł. pr. importowy: Bele proteinowe||Alleria jako kolonia karna dla pracowników fizycznych dostarcza cennej rudy kilku systemom. Trudne warunki życia i praca na sadystycznie długie zmiany oznaczają, że tylko nieliczni, zwykle najbardziej niebezpieczni kryminaliści, są w stanie przetrwać na tej planecie.||
Purgatory=ID planety:  MX-2389 Czyściec|Typ planety: Wulkaniczna|Śr. temp.: 54 C|Populacja: 107 835|Gł. pr. eksportowy: Związki siarki|Gł. pr. importowy: Oczyszczacze CO2|Imperialny Ośrodek Reedukacji na Czyśćcu to ostatni przystanek wrogów Imperium. Zatwardziali przestępcy skazani na reedukację ronią ciche łzy lub błagają o litość nawet w obliczu nadzorców. Wielu uważa, że to słuszna kara dla tych potworów, ale prawdziwe potwory tworzone są w inkubatorach ośrodka. Na ich widok niejeden oszalałby ze strachu.||
Sanctuary=ID planety:   N/A, Sanktuarium|Typ planety: Nieznany|Śr. temp.:   Nieznana|Gł. pr. eksportowy: Nieznany|Gł. pr. importowy: Nieznany||Inkwizytorzy od pewnego czasu podejrzewali, że Grupa Bitewna Polaris nawiązała łączność z niezidentyfikowaną dotąd kolonią. Kolonia ta, znana pod kryptonimem Sanktuarium, jest schronieniem dla najemników, którzy narazili się prawu Imperialnemu. Mimo wykorzystania siatek informatorów do tej pory nie wiadomo, na jakiej planecie leży wspomniana kolonia ani gdzie planeta ta się znajduje.||
Premaka=ID planety:   VX-739 Premaka|Typ planety: Sterylna|Śr. temp.:  Skrajnie zmienna|Populacja:  0, Tylko roboty|Gł. pr. eksportowy: Bele proteinowe|Gł. pr. importowy: Nieznany||Zamieszkana w całości przez roboty planeta Premaka jest ośrodkiem rafinacji i dystrybucji suplementów proteinowych dla posterunków kolonizacyjnych. Choć oficjalnym powodem umieszczenia tego ośrodka w tak nieprzystępnym środowisku jest jego sterylność niektórzy podejrzewają, że komuś może zależeć na utrzymaniu w tajemnicy źródła surowca do produkcji protein.||

SkaarjAA=Imię:  Dominator|Wiek:   Nieznany|Rasa:  Skaarj||Dane:|Brutalny i sprytny. Dominator jest najlepszym przykładem działania kodu wojowników Skaarj.||
SkaarjAB=Imię:  Guardian|Wiek:   Nieznany|Rasa:  Skaarj||Dane:|Celem Guardiana jest objawienie wyższości Skaarjów nad innymi rasami. W wolnym czasie lubi polować na Nali i innych przedstawicieli gorszych ras.||
SkaarjBA=Imię:  Skakruk|Wiek:   Nieznany|Rasa:  Skaarj||Dane:|Niezwykle silny nawet jak na Skaarja. Skakruk chwali się, że jego moc pochodzi od szpiku, który wysysa z kości wrogów.||
SkaarjBB="Imię:  Kraagesh|Wiek:   Nieznany|Rasa:  Skaarj||Dane:|Kraagesh, "Władca Krallów" w języku Skaarjów, znany jest z wykorzystywania Krallów do podbijania poślednich ras.||"
SkaarjCA=Imię:  ClanLord|Wiek:   Nieznany|Rasa:  Skaarj||Dane:|Władca klanu Żelaznej Czaszki budzi strach i szacunek Skaarjów. Jego umiejętności bojowe są niezrównane.||
SkaarjCB=Imię:  Drekorig|Wiek:   Nieznany|Rasa:  Skaarj||Dane:|Drekorig walczy w Turnieju, by odzyskać honor swego klanu. Został on zhańbiony w trakcie wojny ludzi ze Skaarjami, kiedy to zniszczono macierzysty statek Skaarjów.||
SkaarjDA=Imię:  Gaargod|Wiek:   Nieznany|Rasa:  Skaarj||Dane:|Zwycięstwo w turnieju ma być odskocznią dla Gaargoda do pokonania wrogów na macierzystej planecie. Przy okazji chce on odzyskać dla swojej rodziny wysokie stanowisko w klanie Żelaznej Czaszki.||
SkaarjDB="Imię:  Gkublok|Wiek:   Nieznany|Rasa:  Skaarj||Dane:|Nali nazywali Gkubloka "Chodzącą Śmiercią" w czasie, gdy stacjonował na planecie Na Pali.||"

XanRobotAA=Imię:  Virus|Wiek:   Nieznany|Rasa:  Cyborg||Dane:|Maszyna do zabijania pozbawiona wyrzutów sumienia. Virus specjalizuje się w karabinie ASMD.||
XanRobotAB=Imię:  Cyclops|Wiek:   Nieznany|Rasa:  Cyborg||Dane:|Cyclops musi być zamrażany pomiędzy meczami, ponieważ ma trudności z odróżnieniem Turnieju od codziennego życia.||
XanRobotBA=Imię:  Axon|Wiek:   Nieznany|Rasa:  Cyborg||Dane:|Axon był pierwszym wojownikiem Liandri wyposażonym w pancerz i systemy BioMech trzeciej generacji. Ich producentem był legendarny Xan Kriegor.||
XanRobotBB=Imię:  Xan Kriegor|Wiek:   Nieznany|Rasa:  Cyborg||Dane:|Były mistrz Turnieju. Xan Kriegor to postać niemal mityczna. Jego powrót po kilku latach odosobnienia wzbudził ogromny niepokój wśród zawodników.||
XanRobotCA=Imię:  Cathode|Wiek:   Nieznany|Rasa:  Cyborg||Dane:|Korporacja Liandri nie opublikowała żadnych danych dotyczących tego zawodnika.||
XanRobotCB=Imię:  Matrix|Wiek:   Nieznany|Rasa:  Cyborg||Dane:|Korporacja Liandri nie opublikowała żadnych danych dotyczących tego zawodnika.||
XanRobotDA=Imię:  Divisor|Wiek:   Nieznany|Rasa:  Cyborg||Dane:|Korporacja Liandri nie opublikowała żadnych danych dotyczących tego zawodnika.||
XanRobotDB=Imię:  Enigma|Wiek:   Nieznany|Rasa:  Cyborg||Dane:|Korporacja Liandri nie opublikowała żadnych danych dotyczących tego zawodnika.||

ThunderCrashAA=Imię:  Othello|Wiek:   34|Rasa:  Człowiek||Dane:|Umiejętności bojowe Othella objawiły się już w dzieciństwie. W wieku 9 lat Othello wstąpił do elitarnej jednostki Grom.||
ThunderCrashAB=Imię:  Jakob|Wiek:   31|Rasa:  Człowiek||Dane:|Pochodzenie Jakoba jest nieznane - wiadomo tylko, że dorastał w jednej z kolonii wydobywczych w Pasie Centaura.||
ThunderCrashAC=Imię:  Taye|Wiek:   34|Rasa:  Człowiek||Dane:|Umiejętności bojowe Taye'a objawiły się już w dzieciństwie. W wieku 9 lat Taye wstąpił do elitarnej jednostki Grom. Jest bratem-bliźniakiem Othella.||
ThunderCrashBA=Imię:  Azure|Wiek:   39|Rasa:  Człowiek||Dane:|Wychowana w bardzo bogatej rodzinie Azure mogła korzystać z nauk najlepszych wojowników. Implanty wszczepione jej przez specjalistów z najlepszych szpitali rozwinęły jej umiejętności do maksimum.||
ThunderCrashBB=Imię:  Aryss|Wiek:   27|Rasa:  Człowiek||Dane:|Aryss niegdyś była pilotem wojskowym, lecz z czasem zauważyła, że jej zwinność i pewne oko doskonale sprawdzają się na polu walki. Szybko wstąpiła więc do drużyny Grom.||
ThunderCrashCA=Imię:  Riker|Wiek:   31|Rasa:  Człowiek||Dane:|Riker to chodzące połączenie taktyki i stylu. Zawsze stara się znaleźć nowe sposoby na zabicie wrogów. Zdobył już kilka nagród za kreatywność i improwizację.
ThunderCrashCB=Imię:  Picard|Wiek:   32|Rasa:  Człowiek||Dane:|Picard jest poszukiwany przez korporację Izanagi za kradzież projektów tajnego myśliwca kosmicznego. Jednak jego turniejowa sława powoduje, że nie musi się bać aresztowania.
ThunderCrashDA=Imię:  Annika|Wiek:   28|Rasa:  Człowiek||Dane:|Siostra Anniki pracująca jako górnik zginęła w wyniku błędu zarządu Liandri w odmętach planety Vulcana32. Annika wstąpiła do Gromu, by pomóc drużynie zwyciężyć w turnieju i móc podać korporację do sądu. Żąda odszkodowania za śmierć siostry.
ThunderCrashDB=Imię:  Tamika|Wiek:   25|Rasa:  Człowiek||Dane:|Matka Tamiki opuściła ją w młodym wieku, w związku z czym dziewczyna dorastała w domu pełnym mężczyzn. Zgorzkniała do maksimum jest zaprawionym w bojach żołnierzem i zawsze chętnie dokopie facetom.

HellionsAA=Imię:  Outlaw|Wiek:   32|Rasa:  Człowiek||Dane:|Outlaw został zwerbowany przez Hellionów po tym, jak podczas jednej z kryminalnych wycieczek po galaktyce zabił ponoć 300 cywilów.
HellionsAB=Imię:  Garrett|Wiek:   37|Rasa:  Człowiek||Dane:|Garrett jest Hellionem od urodzenia. Uwielbia kobiety i ma wielu fanów wśród nie-Hellionów ze względu na swe grubiańskie zachowanie.
HellionsBA=Imię:  Zarina|Wiek:   24|Rasa:  Człowiek||Dane:|Zarina to naprawdę szalona dziewczyna. Ciągle imprezuje i często walczy pod wpływem różnych substancji. Wierzy, że to jej pomaga.
HellionsBB=Imię:  Kaela|Wiek:   28|Rasa:  Człowiek||Dane:|Kaela to prawdziwa diablica. Jeśli jej okropny język cię nie zabije, zrobi to z pewnością jej giwera.
HellionsCA=Imię:  Kane|Wiek:   29|Rasa:  Człowiek||Dane:|Kane jest nie tylko psychotykiem, ale ma także zaburzenia osobowości, co powoduje, że może w jednej chwili zmienić styl walki.
HellionsCB=Imię:  Baird|Wiek:   26|Rasa:  Człowiek||Dane:|Mówią, że dobrze jest się zadawać z osobami cichymi i spokojnymi. Baird przed walką jest niezwykle spokojny, jednak gdy mecz się zacznie, włącza drugi bieg i nie spocznie, dopóki nie zmiażdży wszystkich przeciwników.
HellionsDA=Imię:  Rae|Wiek:   23|Rasa:  Człowiek||Dane:|Rae i jej siostra Greith zostały znalezione przez Hellionów, kiedy były jeszcze niemowlakami. Hellioni znaleźli je, przeszukując kolonię zniszczoną przez Skaarjów.
HellionsDB=Imię:  Greith|Wiek:   23|Rasa:  Człowiek||Dane:|Greith i jej siostra Rae zostały znalezione przez Hellionów, kiedy były jeszcze niemowlakami. Hellioni znaleźli je, przeszukując kolonię zniszczoną przez Skaarjów.

NewNightmare=Imię:  Abaddon|Wiek:   31|Rasa:  Człowiek||Dane:|Abaddon, przywódca Czarnego Legionu, jest wynikiem zaawansowanych manipulacji genetycznych. Korporacja sponsorująca eksperymenty uznała je za nieudane, ponieważ - choć Abaddon jest niezwykle wydajnym zabójcą - ciągły ból ogarniający jego ciało prawdopodobnie znacznie skróci czas jego życia. Tym samym potencjał komercyjny tej technologii staje się bardzo ograniczony.
Ophelia=Imię:  Ophelia|Wiek:   23|Rasa:  Człowiek||Dane:|Ophelia szybko zrobiła karierę wśród Hellionów i została najmłodszym w historii Hellionem, który wziął udział w Turnieju. Opracowała nawet własną taktykę walki opierającą się na jej ulubionym rodzaju broni, spawarce.

MechaSkaarj=Imię:  Mekkor|Wiek:   Nieznany|Rasa:  Skaarj||Dane:|Mekkor jest członkiem klanu Czarnej Pięści - zatwardziałych przeciwników klanu Żelaznej Czaszki. Ciężko ranny w bitwie testuje w Turnieju nowy cybernetyczny pancerz.||
MechaSkaarjB=Imię:  Skrilax|Wiek:   Nieznany|Rasa:  Skaarj||Dane:|Skrilax, podobnie jak jego brat Mekkor, jest członkiem klanu Czarnej Pięści, zatwardziałych przeciwników klanu Żelaznej Czaszki. W trakcie walki z Żelazną Czaszką został ciężko ranny.||
BarkTooth=Imię:  BarkTooth|Wiek:   32|Rasa:  Człowiek||Dane:|BarkTooth wolałby raczej rozszarpać wroga na kawałki, niż walczyć z nim na dystans. Z tego względu uwielbia wpakować przeciwnikowi cały magazynek Flaka z bliskiej odległości.||
Karag=Imię:  Karag|Wiek:   42|Rasa:  Człowiek||Dane:|Zanim wstąpił do Żelaznej Gwardii, Karag uczył się walki jako kolonialny szeryf. Jego styl i elegancja zyskały mu wielu fanów wśród turniejowej publiczności.||
Necris=Imię:  Kragoth|Wiek:   127|Rasa:  Necris||Dane:|Po kilkuletniej nieobecności Necrisi przygotowują powrót do Turnieju. Kragoth znany jako 'Rzeźnik Gwiazd' jest budzącym strach zabójcą Necris Phayder. Plotka głosi, że kiedyś w pojedynkę zabił całą załogę Krążownika Gwiezdnego ICV.||
NecrisB=Imię:  Thannis|Wiek:   93|Rasa:  Necris||Dane:|Po kilkuletniej nieobecności Necrisi przygotowują powrót do Turnieju. Thannis bierze udział, by dokonać zwiadu.||

